services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: serenite_solidarite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d serenite_solidarite"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [appnet]

  api:
    image: solidarite-kubernetes
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/serenite_solidarite
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      # optionnel: SPRING_JPA_HIBERNATE_DDL_AUTO=update (mieux: Flyway/Liquibase)
    ports:
      - "8080:8080"
    networks: [appnet]

networks:
  appnet:

volumes:
  pgdata: